# https://taskfile.dev
version: "3"

interval: 500ms

silent: true

tasks:
  default: task --list

  prepare-env:
    cmds:
      - task: aliases
      - task: workdir

  aliases:
    desc: "update .bashrc"
    cmds:
      - cmd: echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
      - cmd: echo "complete -F __start_kubectl k" >> /root/.bashrc
      - cmd: echo 'alias download-asset="task -t /tmp/Taskfile.yaml download-asset"' >> /root/.bashrc

  workdir:
    desc: "Create the workdir"
    requires:
      vars:
        - WORKDIR
    cmds:
      - cmd: mkdir -p /workspace/{{.WORKDIR}}/examples

  download-asset:
    desc: "Downloading asset from GitHub"
    dir: "{{.USER_WORKING_DIR}}"
    requires:
      vars:
        - TRACK
        - CHALLANGE
        - FILE
        - WORKDIR
    cmds:
      - cmd: wget https://raw.githubusercontent.com/fullstaq-labs/instruqt-assets/main/{{.TRACK}}/{{.CHALLANGE}}/{{.FILE}}
