apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-frontend
  namespace: imported
spec:
  replicas: 3
  selector:
    matchLabels:
      app: management-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: management-frontend
    spec:
      containers:
        - image: nginx:alpine
          imagePullPolicy: IfNotPresent
          name: nginx
